### ISSUE TITLE
Gagal Install secara Offline di Mesin EFI

### ISSUE THREAD

**Issue by artemtech** [BlankOn/Uluwatu#103]
Pastikan sudah boot dengan mode EFI dari pengaturan BIOS dan menggunakan haftian ketika membuat USB Bootable EFI nya..
1. masuk dalam mode live
2. matikan koneksi internet
3. Install blankon sebagai mana mestinya, 
4. BlankOn gagal dipasang saat pemasangan GRUB, karena tidak mengambil paket grub-efi yang ada di repo CD, melainkan ambil langsung dari repo online.

http://tempel.blankon.in/6377001

**Comment by tuanpembual** [comment]
Butuh utik2 source list pak, 
seperti debian, pas instalasi awal dia akan mounting repo dari cd, trs nulis di file sourcelist.
setelah selesai masang, baris itu ditambahin pagar.

**Comment by artemtech** [comment]
update:
ternyata, installer sudah ambil dari repo lokal CD, hanya saja, paket2 yang diperlukan tidak ditemukan karena beda versi dan ada paket yang belum masuk di repo CD

[Log pemasangan](http://tempel.blankon.in/6377046)
[Isi repo CD](http://tempel.blankon.in/6377047)

**Comment by artemtech** [comment]
solved per jahitan 20180418 dengan menambahkan paket2 yang diperlukan ke repo lokal dalam CD
