### ISSUE TITLE
Dash null

### ISSUE THREAD

**Issue by ganggas95** [BlankOn/Uluwatu#105]
Kalo migrasi dari Ubuntu ke Blankon dan menggunakan directory home ubuntu yang lama saya temukan issue di dash menjadi null.
![image](https://user-images.githubusercontent.com/22877512/41076880-6265c410-6a46-11e8-9267-70ff9cd3cdd5.png)
.

**Comment by herpiko** [comment]
Ikon di dash diwakili oleh berkas `*.desktop`. Bila ingin menambahkan ikon baru, klik kanan ikon aplikasi di menu utama, lalu pilih, `Add to Desktop`

![dash-right-click](https://user-images.githubusercontent.com/2534060/41077111-b1a828a6-69c9-11e8-8b7f-7a191670969b.jpg)
![dash-desktop](https://user-images.githubusercontent.com/2534060/41077113-b1fb36e0-69c9-11e8-8fc8-9956546a0b4b.png)
