### ISSUE TITLE
irgsh error submit

### ISSUE THREAD

**Issue by antosamalona** [BlankOn/Uluwatu#14]
irgsh mengalami galat ketika submit untuk build job.
![selection_008](https://cloud.githubusercontent.com/assets/10811987/24071771/58253764-0c15-11e7-9123-930dbf0318fa.png)

**Comment by herpiko** [comment]
Sudah beres, disebabkan nilai untuk path sertifikat yang dipasang di sisi irgsh-web (irgsh_web/localsettings.py) bukan full path. 

- mesti full path
- permissionnya mesti bisa dibaca oleh user yang menjalankan fastcgi-nya irgsh-web
