### ISSUE TITLE
Fitur :: Manual Page (man) berbahasa Indonesia dengan nama 'dok'

### ISSUE THREAD

**Issue by i5um41ru** [BlankOn/Uluwatu#37]
Pak/Bu, saya ingin agar ada `man` (manual page) berbahasa Indonesia. Pada dasarnya merupakan aplikasi `man` dengan nama baru `dok`, cara akses pun sama, cuma basisdata-nya berbeda.

**Comment by herpiko** [comment]
@i5um41ru usulan fitur masuknya ke sini, https://github.com/BlankOn/Uluwatu/issues/4
