### ISSUE TITLE
[Apikasi Khas BlankOn] Aplikasi Belajar Bahasa

### ISSUE THREAD

**Issue by yusrideb** [BlankOn/Uluwatu#39]
Aplikasi belajar bahasa, sangat penting terutama bahasa Inggris, dengan cara pembelajarannya kurang lebih sama seperti : 
https://www.nhk.or.jp/lesson/indonesian/

**Comment by herpiko** [comment]
@yusrideb usulan fitur masuknya ke sini, https://github.com/BlankOn/Uluwatu/issues/4
