### ISSUE TITLE
url pelaporan kutu di banner partoedi

### ISSUE THREAD

**Issue by artemtech** [BlankOn/Uluwatu#69]
alihkan url pelaporan kutu dari dev.boi/tickets ke github

**Comment by herpiko** [comment]
@antosamalona https://github.com/BlankOn/blankon-installer/releases/tag/1.40

**Comment by artemtech** [comment]
fixed, jahitan 20171016
url sudah dipindahkan ke https://github.com/BlankOn/Uluwatu/issues ,
