### ISSUE TITLE
manokwari tidak memunculkan panel bawah

### ISSUE THREAD

**Issue by artemtech** [BlankOn/Uluwatu#70]
jahitan - 20170929-001
- paket manokwari 1.0.14

setelah masuk destop live tidak ada panel bawah,
- sebelumnya, di paket manokwari 1.0.13 masih menampilkan panel bawah

**Comment by alunux** [comment]
Yup, saya juga mengkonfirmasi hal ini dengan `manokwari 1.0.14 - 5d321e3` di Fedora 26. Ada kemungkinan terjadi regresi saat pengembangan dan sepertinya terjadi di sisi frontend nya.

**Comment by herpiko** [comment]
Akan saya cek.

**Comment by alunux** [comment]
@herpiko saya ikut test ya, pak.

**Comment by herpiko** [comment]
@alunux siap!

**Comment by alunux** [comment]
@herpiko sip, dah dapat. Gegara ini https://github.com/BlankOn/manokwari/commit/75130e6bd81d6fdc2f7e7986fc2fecbec5780d67. Sudah saya coba revert dan fixed di saya.

**Comment by herpiko** [comment]
@alunux Cepet amat (woot). My bad. *_*

**Comment by alunux** [comment]
@herpiko sedang bersemangat pak, alhamdulillah.

**Comment by herpiko** [comment]
@showcheap mau cobain? Sambil uji pakai `./scripts/deploy.sh`

**Comment by herpiko** [comment]
https://github.com/BlankOn/manokwari/pull/87

**Comment by herpiko** [comment]
@antosamalona mohon dipaketkan, 

https://github.com/BlankOn/manokwari/releases/tag/1.0.15

**Comment by alunux** [comment]
@herpiko sip, there is no regression, tested on `manokwari-1.0.15 - 991fe87f`

**Comment by herpiko** [comment]
@antosamalona please do not add `Silakan diuji` label if the release has not packaged into the arsip-dev repository yet.

**Comment by herpiko** [comment]
New release, https://github.com/BlankOn/manokwari/releases/tag/1.0.16

**Comment by artemtech** [comment]
fixed di jahitan 20171016, versi 1.0.15
