### ISSUE TITLE
tidak bisa melakukan lockscreen karena gnome-screensaver tidak autostart

### ISSUE THREAD

**Issue by artemtech** [BlankOn/Uluwatu#71]
versi jahitan: 20171016-001

start manual dengan perintah:
`gnome-screensaver`

**Comment by antosamalona** [comment]
Sudah ditambal. Silahkan diuji kembali.

**Comment by artemtech** [comment]
@antosamalona , masih belum bisa lockscreen di jahitan terakhir [ 20171018 ]

**Comment by artemtech** [comment]
jahitan 20171118 masih belum bisa lockscreen
setelah mengganti file di /etc/xdg/autostart/gnome-screensaver.desktop, berhasil autostart gnome-screensaver nya

http://tempel.blankon.in/5739013

**Comment by antosamalona** [comment]
Silahkan diuji kembali pak. sudah ditambal.
