### ISSUE TITLE
pasca install tidak bisa pasang aplikasi lantaran sources.list meleset

### ISSUE THREAD

**Issue by artemtech** [BlankOn/Uluwatu#73]
versi jahitan: 20171018
paket terkait: blankon-repository-setup
semula berisi
- arsip-dev.blankonlinux.or.id/uluwatu uluwatu xxx
seharusnya:
+ arsip-dev.blankonlinux.or.id/blankon uluwatu xxx

**Comment by antosamalona** [comment]
Sudah ditambal.

**Comment by artemtech** [comment]
fixed di jahitan 20171019 - 001
