### ISSUE TITLE
tidak bisa mencoba pasang aplikasi saat mode live

### ISSUE THREAD

**Issue by artemtech** [BlankOn/Uluwatu#74]
versi jahitan 20171018
skenario:
- pastikan sudah terkoneksi internet
- jalankan mode live
- coba pasang aplikasi kecil, seperti htop (226kB) :
`sudo apt install htop`
- muncul galat kurang lebih:
`E: You dont have enough free space in  /var/cache/apt/archives`

**Comment by herpiko** [comment]
@artemtech ini livenya dengan apa pak? USB flashdisk? DVD?

**Comment by artemtech** [comment]
masih di mesin virtual pak @herpiko

**Comment by artemtech** [comment]
maaf belum sempat tutup,
sudah fixed per jahitan 20171106
