### ISSUE TITLE
ganti workspace hanya memunculkan layar biru

### ISSUE THREAD

**Issue by artemtech** [BlankOn/Uluwatu#75]
paket terkait: manokwari > 1.0.13
Skenario:
```
1. saat ini ada di workspace default desktop manokwari ( Workspace 1 )
2. Klik tombol ganti workspace di pojok kanan atas
3. Pilih sembarang workspace (2,3,4)
4. Setelah kita dialihkan ke workspace terkait, deskop manokwari tidak muncul secara sempurna
(background tidak ada, semua panel hilang),
hanya memunculkan layar biru,
dan bekas jendela aplikasi di Workspace 1 tetapi tidak bisa diakses.
```
Sehingga dengan kejadian 4, tidak bisa kembali ke workspace manapun

**Comment by alunux** [comment]
Apakah isu ini cuman terjadi di BlankOn Uluwatu? Saya pakai manokwari-1.0.16 di Fedora 26 tidak dapat memproduksi ulang isu ini.

**Comment by gryphc** [comment]
Lapor pak,
Di Uluwatu RC2 bugnya masih ada.

**Comment by artemtech** [comment]
@alunux, sampai saat ini, isu hanya bisa direproduksi di BlankOn Uluwatu.. Manokwari di distro lain masih belum saya uji

**Comment by alunux** [comment]
Kalau boleh tau, BlankOn Uluwatu pakai GNOME stack versi berapa? Oh iya, mungkin ketika galatnya terjadi, bisa lihat lognya dan dilampirkan di sini untuk membantu debugging.

**Comment by artemtech** [comment]
#77

**Comment by artemtech** [comment]
@alunux , pakai GNOME versi 3.26

**Comment by hahn** [comment]
saya coba di opensuse (versi 1.0.16) galat serupa tidak ada. Cuma pas ganti ke workspace baru agak ngelag beberapa milidetik (dan warnanya biru)

**Comment by artemtech** [comment]
per jahitan 20171811 sudah fixed
versi manokwari di uluwatu: 1.0.16.-0blankon1
