### ISSUE TITLE
Tampilan wallpaper tidak proporsional di layar kecil

### ISSUE THREAD

**Issue by artemtech** [BlankOn/Uluwatu#76]
konfigurasi default yang digunakan adalah `stretch`, sebagai solusi bisa digunakan mode `center`

```
$ gsettings get org.gnome.desktop.background picture-options
'stretched'
```

**Comment by alunux** [comment]
Mungkin bisa coba mode `zoom` ketimbang `center` karena akan berpengaruh jika ukuran gambar lebih kecil dibanding resolusi layar.

**Comment by antosamalona** [comment]
Silahkan diuji kembali. Sudah saya ubah ke zoom.

**Comment by artemtech** [comment]
siap pak anto, besok pagi saya uji

**Comment by antosamalona** [comment]
Silahkan diuji kembali pak @artemtech

**Comment by herpiko** [comment]
https://github.com/BlankOn/manokwari/releases/tag/1.0.17

**Comment by herpiko** [comment]
https://github.com/BlankOn/manokwari/releases/tag/1.0.18

**Comment by amrikasir** [comment]
bisa juga menggunakan Gnome Tweak Tools untuk menangani hal ini pak.. :grinning:

**Comment by artemtech** [comment]
sudah solved dengan versi manokwari 1.0.18
