### ISSUE TITLE
Masalah login ke web panduan boi

### ISSUE THREAD

**Issue by FaiqAminuddin** [BlankOn/Uluwatu#90]
Masalah: Web dapat diakses tapi pengguna tidak dapat login

**Comment by FaiqAminuddin** [comment]
Pihak sponsor sayembara menulis pada web panduan .boi ini beharap sebelum 23 Maret web sudah dapat diakses kembali dan penggunan dapat login sehingga dapat posting artikel. Pihak sposor berencana sosialisasi sayembara pada acara LOCI.

**Comment by herpiko** [comment]
Terjadi lagi setelah pasang paket-paket terkait php / curl.

**Comment by herpiko** [comment]
1. Remove any duplicated cacerts
2. Remove /comment any config lines that related to cur.cacert on any php.ini under /etc/php5/**/*
3. Then run `sudo update-ca-certificates --fresh`
