### ISSUE TITLE
Nautilus file manager tidak bisa akses partisi

### ISSUE THREAD

**Issue by gryphc** [BlankOn/Uluwatu#91]
Nautilus file manager tidak bisa akses partisi
![screenshot from 2018-03-07 06-03-46](https://user-images.githubusercontent.com/12582361/37064985-a93d5064-21d1-11e8-8a7a-92d8d16d83bb.png)

**Comment by artemtech** [comment]
sepertinya biang keladi untuk permasalahan ini juga seperti permasalahan #93 terkait masalah `policykit-1-gnome`

**Comment by artemtech** [comment]
pak @gryphc , apakah isu ini masih berlanjut setelah update paket `policykit-1-gnome` ?

**Comment by gryphc** [comment]
Udah OK Pak...

**Comment by artemtech** [comment]
solved dengan `policykit-1-gnome` versi `0.105-6blankon1`
