### ISSUE TITLE
Synaptic

### ISSUE THREAD

**Issue by gryphc** [BlankOn/Uluwatu#93]
Tidak bisa membuka synaptic dari BlankOn menu, harus lewat terminal: sudo synaptic
Tidak bisa membuka daftar repo dari Setting > Repositories, yg muncul cuma jendela untuk apdate repo list
![screenshot from 2018-03-07 06-38-54](https://user-images.githubusercontent.com/12582361/37065358-100a1c40-21d3-11e8-85e9-e71ca3161ca3.png)

**Comment by artemtech** [comment]
terima kasih pak @gryphc atas laporannya, 
mungkin solusi yang bisa ditawarkan untuk ini:
1. perbaikan paket `policykit-1-gnome` untuk mengatasi tidak bisa menjalankan synaptic
berkas terkait ada di `/etc/xdg/autostart/polkit-gnome-authentication-agent-1.desktop`
http://tempel.blankon.in/6027430

2. untuk template uluwatu nya karena masih belum dimasukkan lagi di `/usr/share/python-apt/templates/Blankon.info` , ...

**Comment by antosamalona** [comment]
Silahkan diuji kembali, pak.
Cc: @gryphc @artemtech

**Comment by artemtech** [comment]
:white_check_mark:  case 1 :   
   `Tidak bisa membuka synaptic dari BlankOn menu, harus lewat terminal: sudo synaptic`   
   sudah aman setelah perbaikan paket `policykit-1-gnome` 
:negative_squared_cross_mark:  case 2:  
  `Synaptic > Setting > Repositories yg muncul cuma jendela untuk update repo list`
   belum solved

**Comment by artemtech** [comment]
untuk case 2, sepertinya bisa solved dengan isu ini pak @antosamalona 
#78

**Comment by gryphc** [comment]
Case 1 udah OK pak...
Sekalian bugs pada nautilus juga udah solve dengan update policykit-1-gnome

**Comment by artemtech** [comment]
solved per jahitan 20180423
